import cadquery as cq
from cadquery.vis import show

# --- Part 1: U-shaped extrusion ---
part_1_scale = 0.75
part_1_sketch_points = [
    (0.0, 0.0),
    (0.0, 0.0015),
    (0.0015, 0.0015),
    (0.0015, 0.003),
    (0.003, 0.003),
    (0.003, 0.0045),
    (0.0045, 0.0045),
    (0.0045, 0.006),
    (0.006, 0.006),
    (0.006, 0.0075),
    (0.0075, 0.0075),
    (0.0075, 0.009),
    (0.009, 0.009),
    (0.009, 0.0105),
    (0.0105, 0.0105),
    (0.0105, 0.012),
    (0.012, 0.012),
    (0.012, 0.0135),
    (0.0135, 0.0135),
    (0.0135, 0.015),
    (0.015, 0.015),
    (0.015, 0.0165),
    (0.0165, 0.0165),
    (0.0165, 0.018),
    (0.018, 0.018),
    (0.018, 0.0195),
    (0.0195, 0.0195),
    (0.0195, 0.021),
    (0.021, 0.021),
    (0.021, 0.0225),
    (0.0225, 0.0225),
    (0.0225, 0.024),
    (0.024, 0.024),
    (0.024, 0.0255),
    (0.0255, 0.0255),
    (0.0255, 0.027),
    (0.027, 0.027),
    (0.027, 0.0285),
    (0.0285, 0.0285),
    (0.0285, 0.03),
    (0.03, 0.03),
    (0.03, 0.0315),
    (0.0315, 0.0315),
    (0.0315, 0.033),
    (0.033, 0.033),
    (0.033, 0.0345),
    (0.