import cadquery as cq
from cadquery.vis import show

# --- Part 1: Cylinder ---
part_1_radius = 0.375 * 0.75  # Sketch radius scaled
part_1_height = 0.55

part_1 = cq.Workplane("XY").circle(part_1_radius).extrude(part_1_height)

# --- Coordinate System Transformation for Part 1 ---
part_1 = part_1.rotate((0, 0, 0), (1, 0, 0), -90)
part_1 = part_1.rotate((0, 0, 0), (0, 0, 1), -90)
part_1 = part_1.translate((0, 0.55, 0))

# --- Assembly ---
assembly = part_1

# --- Export to STL ---
cq.exporters.export(assembly, "./stlcq/0018/00184878.stl")</s>

import cadquery as cq
from cadquery.vis import show

# --- Parameters ---
sketch_scale = 0.75
extrude_depth = 0.55

# --- Part 1: Cylinder ---
part_1_radius = 0.375 * sketch_scale
part_1_height = extrude_depth

part_1 = cq.Workplane("XY").circle(part_1_radius).extrude(part_1_height)

# --- Coordinate System Transformation for Part 1 ---
part_1 = part_1.rotate((0, 0, 0), (1, 0, 0), -90)
part_1 = part_1.rotate((0, 0, 0), (0, 0, 1), -90)
part_1 = part_1.translate((0, 0.55, 0))

# --- Assembly ---
assembly = part_1

# --- Export to STL ---
cq.exporters.export(assembly, "./stlcq/0018/00184878.stl")